filme/urls.py
# url - view - template
from django.urls import path, reverse_lazy
from .views import Homefilmes, Homepage, Detalhesfilme, PesquisaFilme, PaginaPerfil, Criarconta
from django.contrib.auth import views as auth_view

app_name = 'filme'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),   # aqui
    path('filmes/', Homefilmes.as_view(), name='homefilmes'),
    path('filmes/<int:pk>', Detalhesfilme.as_view(), name = 'detalhesfilme'),
    path('pesquisa/', PesquisaFilme.as_view(), name = 'pesquisafilme'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html') , name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='logout.html') , name='logout'),
    path('editarperfil/<int:pk>', PaginaPerfil.as_view(), name='editarperfil'),
    path('criarconta/', Criarconta.as_view(), name='criarconta'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name='editarperfil.html',
                                                             success_url=reverse_lazy('filme.homefilmes')), name='mudarsenha'),
]

uniflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('filme.urls', namespace='filme')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

# Create your models here.

LISTA_CATEGORIA = (
    ("ADMINISTRACAO", "Administração"),
    ("ANALISES", "Análises"),
    ("APRESENTACAO", "Apresentação"),
    ("BANCO DE DADOS", "Banco de Dados (SGBD)"),
    ("COMPUTACAO EM NUVEM","Computação em Nuvem"),
    ("INTELIGENCIA ARTIFICIAL", "Inteligência Artificial"),
    ("PROGRAMACAO", "Programação"),
    ("OUTROS", "Outros"),
)


# Criar o filme
class Filme(models.Model):
    titulo = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumb_filmes')
    descricao = models.TextField(max_length=1000)
    categoria = models.CharField(max_length=25, choices=LISTA_CATEGORIA)
    visualizacao = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)

    def __str__(self):
     return self.titulo

# Criar episódios

class Episodio(models.Model):
    filme = models.ForeignKey("Filme", related_name= "episodios", on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    video = models.URLField()

    def __str__(self):
     return self.filme.titulo +" - " + self.titulo

class Usuario(AbstractUser):
    filmes_vistos = models.ManyToManyField("Filme")

filme/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms


class FormHomepage(forms.Form):
    email = forms.EmailField(label=False)

class CriarContaForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')

filme/views.py
from django.shortcuts import render, redirect, reverse
from .models import Filme, Usuario
from .forms import CriarContaForm, FormHomepage
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin



# Create your views here.
# def homepage(request):
#     return render(request, "homepage.html")

class Homepage(FormView):
    template_name = "homepage.html"
    form_class = FormHomepage

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:

            return redirect('filme:homefilmes')
        else:
            return super().get(request, *args, **kwargs)

    def get_success_url(self):
        email = self.request.POST.get("email")
        usuarios = Usuario.objects.filter(email=email)
        if usuarios:
            return reverse('filme:login')
        else:
            return reverse('filme:criarconta')
        pass


# url - view - html
# def homefilmes(request):
#     context = {}
#     lista_filmes = Filme.objects.all()
#     context ['lista_filmes'] = lista_filmes
#     return render(request, "homefilmes.html", context)

class Homefilmes(LoginRequiredMixin, ListView):
    template_name = "homefilmes.html"
    model = Filme
    # object_list

class Detalhesfilme(LoginRequiredMixin, DetailView):
    template_name = "detalhesfilme.html"
    model = Filme
    # object -> 1 item do nosso modelo

    def get(self, request, *args, **kwargs):
        filme = self.get_object()
        filme.visualizacao += 1
        filme.save()
        usuario = request.user
        usuario.filmes_vistos.add(filme)
        return super(Detalhesfilme, self ).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(Detalhesfilme, self).get_context_data(**kwargs)
        # filtrar a minha tabela de filmes pegando os filmes cuja categoria é igual a categoria do filme da página
        # self.get_object()
        filmes_relacionados = Filme.objects.filter(categoria = self.get_object().categoria)[0:5]
        context["filmes_relacionados"] = filmes_relacionados
        return context

class PesquisaFilme(LoginRequiredMixin, ListView):
    template_name = "pesquisa.html"
    model = Filme
    # object_list

    def get_queryset(self):
        termo_pesquisa = self.request.GET.get("query")
        if termo_pesquisa:
            object_list = self.model.objects.filter(titulo__icontains = termo_pesquisa)
            return object_list
        else:
            return None

class PaginaPerfil(LoginRequiredMixin, UpdateView):
    template_name = "editarperfil.html"
    model = Usuario
    fields = ['first_name', 'last_name', 'email']

    def get_success_url(self):
        return reverse('filme:homefilmes')


class Criarconta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('filme:login')

filme/templates/detalhesfilme.html
{% extends 'base.html' %}

{% block titulo %}
HomeFilmes Uniflix
{% endblock %}

{% block content %}

<main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.thumb.url }}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{object.titulo}}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{ object.descricao|slice:":200" }}...
                </p>
                <div class="flex my-4">
                    <a href="{{ object.episodios.first.video }}">
                        <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                            <ion-icon name="play" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium">
                                Play
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        </section>
        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-3xl font-medium">
                    Descrição
                </h2>
                <div class="flex justify-left  items-center min-w-full  movie_lis">
                    <p class="text-gray-100 text-lg">
                        {{ object.descricao }}
                        <br>
                        <br>
                        Visualizações: {{ object.visualizacao }}
                        Visualizações:
                    </p>
                </div>

                <div style='margin-top:2rem;margin-bottom:2rem;'>
                    <h2 class="text-gray-200 text-3xl font-medium">
                        Episódios

                    </h2>
                    {% for episodio in object.episodios.all %}
                        <h3 class='text-lg'>
                            <a href = " {{episodio.video}} ">
                                <p> Espisódio {{ forloop.counter }} : {{ episodio.titulo }}</p>
                            </a>
                        </h3>
                    {% endfor %}

                </div>

            </div>
        </section>

        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Relacionados
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                    {% for filme in filmes_relacionados %}
                    <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                        <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt="">
                        </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>

</main>

{% endblock %}

filme/templates/editarperfil.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block titulo %}
Editar Perfil
{% endblock %}

{% block content %}


    <header class="min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/big-data (nova).jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h2 class ="text-2xl"> {{ user.username }} </h2>
            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
                    {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Editar Perfil</button>
            </form>
            <small><a href="{% url 'filme:mudarsenha' %}">Quer mudar sua senha?</a></small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2021</li>
            <li> Feito com Python (Django)</li>
            <li>Fatec Ipiranga</li>
        </ul>
    </footer>


{% endblock %}

filme/templates/homefilmes - Rev. 1.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
HomeFilmes Uniflix
{% endblock %}

{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
       <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{ filme_destaque.thumb.url }}');">
            <div class="bg-black bg-opacity-50 p-4 rounded-md">
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{ filme.destaque.titulo }}
                </h2>
                <p class="w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{ filme.destaque.descricao }}
                </p>
                    <div class="flex my-4">
                        <a href="{% url 'filme:detalhesfilme' filme_destaque.pk %}">
                            <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                                <ion-icon name="play" class="text-2xl"></ion-icon>
                                <span class="ml-3 font-medium">
                                    Play
                                </span>
                            </button>
                        </a>
                    </div>
            </div>
        </section>
        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Novo
                </h2>
                <div class="wrapper">
                  <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2" class="arrow__btn text-6xl page">‹</a>
                      {% for filme in lista_filmes_recentes %}
                          {% if forloop.counter < 5  %}
                              <div class="item h-64 w-1/4 m-4">
                                  <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                    <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                  </a>
                              </div>
                          {% endif %}
                      {% endfor %}
                        <a href="#section2" class="arrow__btn text-6xl">›</a>
                  </section>
                  {% if lista_filmes_recentes|length > 4 %}
                      <section id="section2" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1" class="arrow__btn text-6xl">‹</a>
                        {% for filme in lista_filmes_recentes %}
                             {% if forloop.counter > 4  %}
                             <div class="item h-64 w-1/4 m-4">
                                 <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                 <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                 </a>
                             </div>
                             {% endif %}
                        {% endfor %}
                        <a href="#section1" class="arrow__btn text-6xl">›</a>
                      </section>
                  {% endif %}
                </div>
            </div>
        </section>



        <section class="bg-primary_black flex justify-center py-10">
        <div class="p-8 w-10/12 relative">
        <h2 class="text-gray-200 text-2xl font-medium">
            Continuar Assistindo
        </h2>
        <div class="wrapper">
            <section id="section1vistos" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2vistos" class="arrow_btn text-6xl page"></a>
                {% for filme in request.user.filmes_vistos.all %}
					{% if forloop.counter < 5 %}
						<div class="item h-64 w-1/4">
							<a href="{% url 'filme:detalhesfilme' filme.pk %}">
								<img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
							</a>
						</div>
					{% endif %}
				{% endfor %}
				<a href="#section2vistos" class="arrow_btn text-6xl"></a>
			</section>
			{% if request.user.filmes_vistos.all|length < 4 %}
				<section id="section2vistos" class="flex flex-nowrap items-center justify-center">
					<a href="#sectionlmalta" class="arrow_btn text-6xl"></a>
					{% for filme in request.user.filmes_vistos.all %}
						{% if forloop.counter > 4 %}
							<div class="item h-64 w-1/4 h-4">
								<a href="{%  url 'filme:detailestlime' filme.pk %}">
								<img src="{%  filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
								</a>
							</div>
						{% endif %}
					{% endfor %}
					<a href="#section2vistos" class="arrow_btn text-6xl"></a>
				</section>
			{% endif %}
		</div>
	</div>
</section>

        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Em Alta
                </h2>
                <div class="wrapper">
                  <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2" class="arrow__btn text-6xl page">‹</a>
                      {% for filme in lista_filmes_recentes %}
                          {% if forloop.counter < 5  %}
                              <div class="item h-64 w-1/4 m-4">
                                  <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                    <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                  </a>
                              </div>
                          {% endif %}
                      {% endfor %}
                        <a href="#section2" class="arrow__btn text-6xl">›</a>
                  </section>
                  {% if lista_filmes_recentes|length > 4 %}
                      <section id="section2" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1" class="arrow__btn text-6xl">‹</a>
                        {% for filme in lista_filmes_recentes %}
                             {% if forloop.counter > 4  %}
                             <div class="item h-64 w-1/4 m-4">
                                 <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                 <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                 </a>
                             </div>
                             {% endif %}
                        {% endfor %}
                        <a href="#section1" class="arrow__btn text-6xl">›</a>
                      </section>
                  {% endif %}
                </div>
            </div>
        </section>


</main>
{% endblock %}

filme/templates/homefilmes.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
HomeFilmes Uniflix
{% endblock %}

{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
       <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{ filme_destaque.thumb.url }}');">
            <div class="bg-black bg-opacity-50 p-4 rounded-md relative z-10">
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{ filme.destaque.titulo }}
                </h2>
                <p class="w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{ filme.destaque.descricao }}
                </p>
                    <div class="flex my-4">
                        <a href="{% url 'filme:detalhesfilme' filme_destaque.pk %}">
                            <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                                <ion-icon name="play" class="text-2xl"></ion-icon>
                                <span class="ml-3 font-medium">
                                    Play
                                </span>
                            </button>
                        </a>
                    </div>
            </div>
        </section>
        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Novo
                </h2>
                <div class="wrapper">
                  <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2" class="arrow__btn text-6xl page">‹</a>
                      {% for filme in lista_filmes_recentes %}
                          {% if forloop.counter < 5  %}
                              <div class="item h-64 w-1/4 m-4">
                                  <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                    <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                  </a>
                              </div>
                          {% endif %}
                      {% endfor %}
                        <a href="#section2" class="arrow__btn text-6xl">›</a>
                  </section>
                  {% if lista_filmes_recentes|length > 4 %}
                      <section id="section2" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1" class="arrow__btn text-6xl">‹</a>
                        {% for filme in lista_filmes_recentes %}
                             {% if forloop.counter > 4  %}
                             <div class="item h-64 w-1/4 m-4">
                                 <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                 <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                 </a>
                             </div>
                             {% endif %}
                        {% endfor %}
                        <a href="#section1" class="arrow__btn text-6xl">›</a>
                      </section>
                  {% endif %}
                </div>
            </div>
        </section>


    <section class="bg-primary_black flex justify-center py-10">
    <div class="p-8 w-10/12 relative">
        <h2 class="text-gray-200 text-2xl font-medium">
            Continuar Assistindo
        </h2>
        <div class="wrapper">
            <!-- Primeira seção de filmes -->
            <section id="section1vistos" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2vistos" class="arrow_btn text-6xl page">‹</a>
                {% for filme in request.user.filmes_vistos.all %}
                    {% if forloop.counter <= 4 %}
                        <div class="item h-64 w-1/4 m-4">
                            <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}
                <a href="#section2vistos" class="arrow_btn text-6xl">›</a>
            </section>

            <!-- Segunda seção de filmes (se necessário) -->
            {% if request.user.filmes_vistos.all|length > 4 %}
                <section id="section2vistos" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section1vistos" class="arrow_btn text-6xl">‹</a>
                    {% for filme in request.user.filmes_vistos.all %}
                        {% if forloop.counter > 4 %}
                            <div class="item h-64 w-1/4 m-4">
                                <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                    <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                </a>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <a href="#section1vistos" class="arrow_btn text-6xl">›</a>
                </section>
            {% endif %}
        </div>
    </div>
</section>



        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Em Alta
                </h2>
                <div class="wrapper">
                  <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2" class="arrow__btn text-6xl page">‹</a>
                      {% for filme in lista_filmes_recentes %}
                          {% if forloop.counter < 5  %}
                              <div class="item h-64 w-1/4 m-4">
                                  <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                    <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                  </a>
                              </div>
                          {% endif %}
                      {% endfor %}
                        <a href="#section2" class="arrow__btn text-6xl">›</a>
                  </section>
                  {% if lista_filmes_recentes|length > 4 %}
                      <section id="section2" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1" class="arrow__btn text-6xl">‹</a>
                        {% for filme in lista_filmes_recentes %}
                             {% if forloop.counter > 4  %}
                             <div class="item h-64 w-1/4 m-4">
                                 <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                                 <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                 </a>
                             </div>
                             {% endif %}
                        {% endfor %}
                        <a href="#section1" class="arrow__btn text-6xl">›</a>
                      </section>
                  {% endif %}
                </div>
            </div>
        </section>


</main>
{% endblock %}

filme/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Homepage Uniview
{% endblock %}

{% block head %}

    <style>
        #id_email{

        width: 100%;
        height: 50px;
        color: #000000;
        padding: 5xp 5px;

        }

    </style>

{% endblock %}

{% block content %}

    <header class="min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/big-data (nova).jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">

            <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
                Plataforma de apoio aos estudantes e colaboradores
            </h1>
            <h3 class="text-xl md:text-xl py-5">
                Acesse onde quiser.
            </h3>
            <h4 class="text-sm md:text-lg pb-3">
                Quer começar? Coloque seu e-mail abaixo para acessar.
            </h4>

            <div class="w-full flex justify-center">
                <div class="flex justify-center items-center w-11/12 md:w-10/12">
                    <form method="post" class="w-6/12 justify-center">
                        {% csrf_token %}
                        <div class="flex flex-grow items-stretch">
                            {{ form }}
                        <button class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                            <span>
                                Acessar
                            </span>
                            <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                        </button>
                        </div>
                    </form>
                    </a>
                </div>
            </div>

        </div>
    </header>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
               Interagir com o conteúdo.
            </h2>
            <h5 class="md:text-xl text-lg">
                TI, IA, BD, Dados, Cloud, e mais.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/tv.png' %}" class="w-8/12" alt="">
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class='md:w-1/2 flex justify-center items-center '>
            <img src="{% static 'images/mobile-0819.jpg' %}" class="w-8/12" alt="">
        </div>

        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Interação Visual.
            </h2>
            <h5 class="md:text-xl text-lg">
                Save seus vídeos favoritos.
            </h5>
        </div>

    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Crie sua prória conta.
            </h2>
            <h5 class="md:text-xl text-lg">

            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/netflix_kid.jpg' %}" class="w-8/12" alt="">
        </div>
    </section>
    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2024</li>
            <li> Feito com Python (Django)</li>
            <li>Fatec Ipiranga</li>
        </ul>
    </footer>


{% endblock %}

templates/navbar.html
{% load static %}
<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50" >
    <div class = "w-6/12">
        <a href="/">
            <img class = "w-3/12" src = "{% static 'images/uniflix.png' %}">
        </a>
    </div>

    <div class = "w-6/12 flex flex-nowrap justify-end">
         {%if user.is_authenticated%}
            <div class="mr-2">
                <form method="get" action="{% url 'filme:pesquisafilme' %}">
                    <input type="text" class="py-1 px-2 rounded-md text-black" name="query" value="{{ request.GET.query }}" placeholder="Pesquisar...">
                    <input type="submit" value="">
                </form>
            </div>
        {% endif %}

        {% if user.is_authenticated %}
             <div class="mr-2">
                 <a href="{% url 'filme:logout' %}">
                     <form method="post" action="{% url 'filme:logout' %}">
                         {% csrf_token %}
                         <button class="bg-red-600 text=white py-1 px-3 rounded-md" type="submit">
                             Sair
                        </button>
                      </form>
                 </a>
              </div>
         {% else %}
             <div class="mr-2">
                 <a href="{% url 'filme:login' %}">
                    <button class="bg-red-600 text=white py-1 px-3 rounded-md">
                        Login
                    </button>
                 </a>
             </div>
        {% endif %}
    </div>

     {% if user.is_authenticated %}
         <div class="mr-2">
             <a href="{% url 'filme:editarperfil' request.user.pk %}">
                 <button class="bg-red-600 text=white py-1 px-3 rounded-md">
                     Perfil
                </button>
             </a>
         </div>
    {% endif %}


</nav>